// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "seadeals-backend/model"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// AccountHolderRepository is an autogenerated mock type for the AccountHolderRepository type
type AccountHolderRepository struct {
	mock.Mock
}

// SendToAccountHolder provides a mock function with given fields: tx, _a1
func (_m *AccountHolderRepository) SendToAccountHolder(tx *gorm.DB, _a1 *model.AccountHolder) (*model.AccountHolder, error) {
	ret := _m.Called(tx, _a1)

	var r0 *model.AccountHolder
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.AccountHolder) *model.AccountHolder); ok {
		r0 = rf(tx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccountHolder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, *model.AccountHolder) error); ok {
		r1 = rf(tx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TakeMoneyFromAccountHolderByOrderID provides a mock function with given fields: tx, orderID
func (_m *AccountHolderRepository) TakeMoneyFromAccountHolderByOrderID(tx *gorm.DB, orderID uint) (*model.AccountHolder, error) {
	ret := _m.Called(tx, orderID)

	var r0 *model.AccountHolder
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *model.AccountHolder); ok {
		r0 = rf(tx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccountHolder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountHolderRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountHolderRepository creates a new instance of AccountHolderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountHolderRepository(t mockConstructorTestingTNewAccountHolderRepository) *AccountHolderRepository {
	mock := &AccountHolderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
