// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "seadeals-backend/model"

	mock "github.com/stretchr/testify/mock"
)

// CourierService is an autogenerated mock type for the CourierService type
type CourierService struct {
	mock.Mock
}

// GetAllCouriers provides a mock function with given fields:
func (_m *CourierService) GetAllCouriers() ([]*model.Courier, error) {
	ret := _m.Called()

	var r0 []*model.Courier
	if rf, ok := ret.Get(0).(func() []*model.Courier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Courier)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCourierService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCourierService creates a new instance of CourierService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCourierService(t mockConstructorTestingTNewCourierService) *CourierService {
	mock := &CourierService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
