// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "seadeals-backend/model"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// AddToNotificationFromModel provides a mock function with given fields: tx, newNotification
func (_m *NotificationRepository) AddToNotificationFromModel(tx *gorm.DB, newNotification *model.Notification) {
	_m.Called(tx, newNotification)
}

// AddToNotificationFromModelForCron provides a mock function with given fields: newNotification
func (_m *NotificationRepository) AddToNotificationFromModelForCron(newNotification *model.Notification) {
	_m.Called(newNotification)
}

type mockConstructorTestingTNewNotificationRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotificationRepository(t mockConstructorTestingTNewNotificationRepository) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
