// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RefreshTokenService is an autogenerated mock type for the RefreshTokenService type
type RefreshTokenService struct {
	mock.Mock
}

// CheckIfTokenExist provides a mock function with given fields: token
func (_m *RefreshTokenService) CheckIfTokenExist(token string) (bool, uint, error) {
	ret := _m.Called(token)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 uint
	if rf, ok := ret.Get(1).(func(string) uint); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(uint)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewRefreshTokenService interface {
	mock.TestingT
	Cleanup(func())
}

// NewRefreshTokenService creates a new instance of RefreshTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRefreshTokenService(t mockConstructorTestingTNewRefreshTokenService) *RefreshTokenService {
	mock := &RefreshTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
