// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RunCronJobHelper is an autogenerated mock type for the RunCronJobHelper type
type RunCronJobHelper struct {
	mock.Mock
}

// RunCronJobs provides a mock function with given fields:
func (_m *RunCronJobHelper) RunCronJobs() {
	_m.Called()
}

type mockConstructorTestingTNewRunCronJobHelper interface {
	mock.TestingT
	Cleanup(func())
}

// NewRunCronJobHelper creates a new instance of RunCronJobHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRunCronJobHelper(t mockConstructorTestingTNewRunCronJobHelper) *RunCronJobHelper {
	mock := &RunCronJobHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
