// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "seadeals-backend/model"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UserRoleRepository is an autogenerated mock type for the UserRoleRepository type
type UserRoleRepository struct {
	mock.Mock
}

// CreateRoleToUser provides a mock function with given fields: _a0, _a1
func (_m *UserRoleRepository) CreateRoleToUser(_a0 *gorm.DB, _a1 *model.UserRole) (*model.UserRole, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.UserRole
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.UserRole) *model.UserRole); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserRole)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, *model.UserRole) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRolesByUserID provides a mock function with given fields: _a0, _a1
func (_m *UserRoleRepository) GetRolesByUserID(_a0 *gorm.DB, _a1 uint) ([]*model.UserRole, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*model.UserRole
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) []*model.UserRole); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserRole)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRoleRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRoleRepository creates a new instance of UserRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRoleRepository(t mockConstructorTestingTNewUserRoleRepository) *UserRoleRepository {
	mock := &UserRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
